data_root: "/data1/zzh/datasets/sensaturban/"
num_points: 20000
max_epoch: 500
batch_size: 2
loss_weight: false
radius: 1

# senstaurban
bev_size: 500
bev_scale: 0.05
bev_range: 12.5
bev_name: "rgb"
num_classes: 13
training_size: 33
voxel_size: 0.2

# checkpoint
load_path: ''
start_epoch: 1
# optimizer
optimizer: 'sgd'
base_learning_rate: 0.02
momentum: 0.98
weight_decay: 0.001

decay_rate: 0.9885531
decay_epoch: 1
first_subsampling_dl: 0.2 # x5
density_parameter: 5.0
activation_fn: 'relu'
init: 'xavier'
bn_eps: 0.000001

grad_norm: 100
in_features_dim: 6
input_features_dim: 6
bottleneck_ratio: 3
first_features_dim: 128
local_aggreagtion: 'adaptive_weight'
adaptive_weight:
  local_input_feature: 'dp'
  reduction: 'mean'
  shared_channels: 1
  fc_num: 1
  weight_softmax: False
  output_conv: False


epoch_steps: 500
validation_size: 50
in_radius: 10.0 # *5
augment_scale_anisotropic: True
augment_symmetries:
  - True
  - False
  - False
augment_rotation: 'vertical'
augment_scale_min: 0.7
augment_scale_max: 1.3
augment_noise: 0.001
augment_color: 0.8

num_workers: 10
val_freq: 1
